global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['medflow_gateway:5000']

  - job_name: 'chat'
    static_configs:
      - targets: ['medflow_chat:5001']

  - job_name: 'config'
    static_configs:
      - targets: ['medflow_config:5002']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']